DATA SEGMENT
AREA DW 100,3,654,54,898,3,125,6666,545,781
COUNT EQU ($-AREA)/2
MAX DW 65535
MIN DW 0
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
           MOV DS,AX
		   MOV SI,OFFSET AREA
		   MOV AX,65535
		   MOV BX,0
		   MOV CX,COUNT
COMPARE: MOV BX,AREA[SI]
		 CMP AX,BX
		 JB NEXCHANGE
		 MOV AX,BX
NEXCHANGE: ADD SI,2
		   LOOP COMPARE
		   MOV MIN,AX
		   MOV AX,0
		   MOV BX,0
		   MOV CX,COUNT
COMPARE2: MOV BX,AREA[SI]
		 CMP BX,AX
		 JB NEXCHANGE2
		 MOV AX,BX
NEXCHANGE2: ADD SI,2
		   LOOP COMPARE2
		   MOV MAX,AX
		   MOV AH,4CH
            INT 21H			
CODE ENDS
END START